spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/qly_nguoidung
    username: postgres
    password: hoang1962001
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-circular-references: true